const actionTypes = Object.freeze({

    //car
    FETCH_STATUS_CARS_SUCCESS: "FETCH_STATUS_CARS_SUCCESS",
    FETCH_STATUS_CARS_FAILED: "FETCH_STATUS_CARS_FAILED",
    FETCH_CARS_STATUS_SUCCESS: "FETCH_CARS_STATUS_SUCCESS",
    FETCH_CARS_STATUS_FAILED: "FETCH_CARS_STATUS_FAILED",
    
    //destination
    FETCH_STATUS_DESTINATIONS_SUCCESS: "FETCH_STATUS_DESTINATIONS_SUCCESS",
    FETCH_STATUS_DESTINATIONS_FAILED: "FETCH_STATUS_DESTINATIONS_FAILED",

     //departure
    FETCH_STATUS_DEPARTURES_SUCCESS: "FETCH_STATUS_DEPARTURES_SUCCESS",
    FETCH_STATUS_DEPARTURES_FAILED: "FETCH_STATUS_DEPARTURES_FAILED",

    //time
    FETCH_ALL_TIME_SUCCESS: "FETCH_ALL_TIME_SUCCESS",
    FETCH_ALL_TIME_FAILED: "FETCH_ALL_TIME_FAILED",

    //user
    FETCH_DETAIL_USER_SUCCESS: "FETCH_DETAIL_USER_SUCCESS",
    FETCH_DETAIL_USER_FAILED: "FETCH_DETAIL_USER_FAILED",
    RESET_USER: 'RESET_USER',
    
    //departure
    GET_ALL_DEPARTURE_SUCCESS: "GET_ALL_DEPARTURE_SUCCESS",
    GET_ALL_DEPARTURE_FAILED: "GET_ALL_DEPARTURE_FAILED",

    //destination
    GET_ALL_DESTINATION_SUCCESS: "GET_ALL_DESTINATION_SUCCESS",
    GET_ALL_DESTINATION_FAILED: "GET_ALL_DESTINATION_FAILED",

    //trips
    SEARCH_TRIPS_SUCCESS: "SEARCH_TRIPS_SUCCESS",
    SEARCH_TRIPS_FAILED: "SEARCH_TRIPS_FAILED",
})

export default actionTypes;